name: CI
on: 
  pull_request_target:
        branches:
            - master
            - main
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ArtiomTr/jest-coverage-report-action@v2
